repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python_venv
        types: [python]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: python_venv
        types: [python]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: python_venv
        types: [python]
