[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
indent = '    '
line_length = 79
multi_line_output = 3
use_parentheses = true
